window.ITEMS_CATALOG = {
  "itens": [
    {
      "id": "it-331e66c8f973813294d7dff4c30f68ed",
      "nome": "Alaúde",
      "tipo": "Insturmento Musical",
      "alcance": "",
      "empunhadura": "duas mãos",
      "habilidade": "Musicas tocadas consomem -1 de energia.",
      "preco": "120-160 Asterics",
      "qtdPorEspaco": 1,
      "tempoUso": "",
      "descricao": "Musicas tocadas consomem -1 de energia."
    },
    {
      "id": "it-331e66c8f973816d8591d1911770af37",
      "nome": "Amuleto da Caçada",
      "tipo": "Artefato",
      "alcance": "",
      "empunhadura": "",
      "habilidade": "",
      "preco": "???",
      "qtdPorEspaco": 1,
      "tempoUso": "",
      "descricao": "Um amuleto criado com o troféu de uma caçada."
    },
    {
      "id": "it-331e66c8f973816e84e7cfe5fd5387b3",
      "nome": "Anestesia",
      "tipo": "Consumível",
      "alcance": "",
      "empunhadura": "",
      "habilidade": "",
      "preco": "100-150 Asterics",
      "qtdPorEspaco": 1,
      "tempoUso": "Ação",
      "descricao": "O usuário fica imune ao efeito de acertos críticos por 1 batalha."
    },
    {
      "id": "it-331e66c8f97381e09793f50d9ef1339b",
      "nome": "Antidoto",
      "tipo": "Consumível",
      "alcance": "",
      "empunhadura": "",
      "habilidade": "",
      "preco": "50-70 Asterics",
      "qtdPorEspaco": 1,
      "tempoUso": "Ação",
      "descricao": "Esse antídoto remove imediatamente o efeito do veneno para o qual foi feito ao ser tomado."
    },
    {
      "id": "it-331e66c8f9738188b24feb0f749c1f76",
      "nome": "Arco Longo",
      "tipo": "Arma Arma de Caça",
      "alcance": "Longo",
      "empunhadura": "duas mãos",
      "habilidade": "Causa 1d6 Perfurante",
      "preco": "160-220 asterics",
      "qtdPorEspaco": 1,
      "tempoUso": "Ação",
      "descricao": "Um arco de madeira, ou outro material flexível, ligado a uma corda elástica e usado para atirar flechas a longa distância. Só ataca usando flechas."
    },
    {
      "id": "it-331e66c8f97381d1a9cafef7ddacee52",
      "nome": "Arsenal de Transmutação",
      "tipo": "Ferramenta",
      "alcance": "",
      "empunhadura": "",
      "habilidade": "Os acúmulos desse Arsenal podem ser usados para substituir qualquer componente.",
      "preco": "100-200",
      "qtdPorEspaco": 1,
      "tempoUso": "",
      "descricao": "Um conjunto de materiais carregado pelo alquimista, pode conter todo tipo material e é muito útil para a realização de transmutações. Cargas Máximas: 10. Carga Inicial: 5. Espaço Ocupado: 2."
    },
    {
      "id": "it-331e66c8f97381a5be22dce3cdfb4792",
      "nome": "Boomerang",
      "tipo": "Arma Arma de Caça",
      "alcance": "Longo",
      "empunhadura": "uma mão",
      "habilidade": "Causa 1d6 de dano de corte",
      "preco": "120-150",
      "qtdPorEspaco": 1,
      "tempoUso": "Ação",
      "descricao": "O boomerang pode ser atirado até um longo alcance, ele bate no primeiro alvo e volta pra você no início de seu próximo turno. Qualquer criatura atingida no caminho de ida ou de volta recebe o dano."
    },
    {
      "id": "it-331e66c8f97381ecb00ec962f3640cf5",
      "nome": "Carapaça Animal",
      "tipo": "Componente",
      "alcance": "",
      "empunhadura": "",
      "habilidade": "",
      "preco": "5-10 Asterics",
      "qtdPorEspaco": 3,
      "tempoUso": "",
      "descricao": "Uma carapaça retirada de um animal, pode ser um casco, um exoesqueleto ou até uma concha."
    },
    {
      "id": "it-331e66c8f973813e8890f9b11451bef5",
      "nome": "Carnes",
      "tipo": "Componente",
      "alcance": "",
      "empunhadura": "",
      "habilidade": "",
      "preco": "10-100 asterics",
      "qtdPorEspaco": 3,
      "tempoUso": "",
      "descricao": "Um pouco de carne retirada de um animal a sua escolha, boa para ser usada em receitas."
    },
    {
      "id": "it-331e66c8f973819b9535dcf83b9fec5d",
      "nome": "Cogumelo Alucinógeno",
      "tipo": "Componente Consumível",
      "alcance": "",
      "empunhadura": "",
      "habilidade": "",
      "preco": "25-30 Asterics",
      "qtdPorEspaco": 5,
      "tempoUso": "",
      "descricao": "Cogumelos especiais que causam alucinações a quem come, são divertidos e até parecem mágicos, mas cuidado, alguns cogumelos só são comestíveis uma vez."
    },
    {
      "id": "it-331e66c8f97381ba93c9cb02e8c9123b",
      "nome": "Dardo Normal",
      "tipo": "Componente",
      "alcance": "",
      "empunhadura": "",
      "habilidade": "Causa 1d6 de dano perfurante",
      "preco": "10-20",
      "qtdPorEspaco": 5,
      "tempoUso": "",
      "descricao": "Um dardo perfurante normal, a distância que chega depende do que foi usado para atirá-lo, atirar com as mão o faz chegar até o alcance médio."
    },
    {
      "id": "it-331e66c8f9738101ba57e80a45bd28d0",
      "nome": "Dardo Venenoso",
      "tipo": "Componente",
      "alcance": "",
      "empunhadura": "",
      "habilidade": "Causa 1d6 de dano perfurante e aplica envenenamento.",
      "preco": "30-50",
      "qtdPorEspaco": 5,
      "tempoUso": "",
      "descricao": "Um dardo perfurante normal, a distância que chega depende do que foi usado para atirá-lo, atirar com as mão o faz chegar até o alcance médio."
    },
    {
      "id": "it-331e66c8f97381d2be15f29cea798aa0",
      "nome": "Erva Alucinógena",
      "tipo": "Componente Consumível",
      "alcance": "",
      "empunhadura": "",
      "habilidade": "",
      "preco": "5-95 Asterics",
      "qtdPorEspaco": 5,
      "tempoUso": "",
      "descricao": "Um punhado de Ervas alucinógenas, quando consumidas podem causa diversos tipos de efeitos ou alucinações ou quem sabe até um bom enjoo."
    },
    {
      "id": "it-331e66c8f97381dbb1cee25ee4cf1974",
      "nome": "Ervas",
      "tipo": "Componente",
      "alcance": "",
      "empunhadura": "",
      "habilidade": "",
      "preco": "5-20",
      "qtdPorEspaco": 5,
      "tempoUso": "",
      "descricao": "Conjunto de Ervas."
    },
    {
      "id": "it-331e66c8f9738145ae1aea9cf6b0a0b3",
      "nome": "Escudo Grande",
      "tipo": "Proteção",
      "alcance": "",
      "empunhadura": "uma mão",
      "habilidade": "Aumenta o bloqueio em +3",
      "preco": "150-200 Asterics",
      "qtdPorEspaco": 1,
      "tempoUso": "",
      "descricao": "Um grande escudo pesado"
    },
    {
      "id": "it-331e66c8f97381d7938eea62ec9c7b5b",
      "nome": "Espada Longa",
      "tipo": "Arma",
      "alcance": "Corpo a Corpo",
      "empunhadura": "mão e meia",
      "habilidade": "Causa 1d6 +2 de dano cortante.",
      "preco": "150-200 Asterics",
      "qtdPorEspaco": 1,
      "tempoUso": "Ação",
      "descricao": "Uma arma grande com cerca de 80 a 100 centímetros muito usadas por cavaleiros, pode possuir diversos formatos de guarda e até formatos variados na lâmina."
    },
    {
      "id": "it-331e66c8f973818ab1b9d2a90626a303",
      "nome": "Esteróides",
      "tipo": "Consumível",
      "alcance": "",
      "empunhadura": "",
      "habilidade": "",
      "preco": "200-300 Asterics",
      "qtdPorEspaco": 1,
      "tempoUso": "Ação",
      "descricao": "Ao tomar o usuário ganha + 2d6 de vida por um combate, além disso, todos os seus ataques corpo a corpo causam +1d6 de dano."
    },
    {
      "id": "it-331e66c8f97381b2b7dddcffbc08fb65",
      "nome": "Facão",
      "tipo": "Arma Arma de Caça",
      "alcance": "Corpo a Corpo",
      "empunhadura": "uma mão",
      "habilidade": "causa 1d6 cortante, concede +2 em testes relacionados a sobrevivência.",
      "preco": "160-180",
      "qtdPorEspaco": 1,
      "tempoUso": "Ação",
      "descricao": "Um facão afiado, bom pra cortar e uma ferramenta de sobrevivência bem útil."
    },
    {
      "id": "it-331e66c8f9738175a3f0dc1d363340a8",
      "nome": "Flauta",
      "tipo": "Insturmento Musical",
      "alcance": "",
      "empunhadura": "duas mãos",
      "habilidade": "",
      "preco": "30-50 Asterics",
      "qtdPorEspaco": 1,
      "tempoUso": "",
      "descricao": "Não ocupa espaço no invetário."
    },
    {
      "id": "it-331e66c8f97381329fb7ce3c3ee10e12",
      "nome": "Flechas",
      "tipo": "Componente",
      "alcance": "",
      "empunhadura": "",
      "habilidade": "",
      "preco": "10-15 Asterics",
      "qtdPorEspaco": 3,
      "tempoUso": "",
      "descricao": "Um objeto aerodinâmico, normalmente feito de madeira e com uma ponta de metal ou pedra."
    },
    {
      "id": "it-331e66c8f973812c8914ca968304d1c1",
      "nome": "Fogo de Alquimista",
      "tipo": "Componente Consumível",
      "alcance": "",
      "empunhadura": "",
      "habilidade": "",
      "preco": "10-50",
      "qtdPorEspaco": 2,
      "tempoUso": "Reação",
      "descricao": "Coloca fogo em uma área de 3x3. Dano de fogo: 1d6"
    },
    {
      "id": "it-331e66c8f97381dd9afbe08375ed339b",
      "nome": "Frasco de Álcool",
      "tipo": "Componente Consumível",
      "alcance": "",
      "empunhadura": "",
      "habilidade": "",
      "preco": "5-10 Asterics",
      "qtdPorEspaco": 2,
      "tempoUso": "",
      "descricao": "Um frasco de mais ou menos 500ml de álcool, é obtido pela fermentação usando plantas ou até combustíveis. Pode ser usado em diversas receitas ou para limpar ou esterilizar algo."
    },
    {
      "id": "it-331e66c8f97381998cbce9111078c571",
      "nome": "Frutas",
      "tipo": "Componente",
      "alcance": "",
      "empunhadura": "",
      "habilidade": "",
      "preco": "5-20 asterics",
      "qtdPorEspaco": 5,
      "tempoUso": "",
      "descricao": "Uma fruta a sua escolha, pode ser comida ou usada em receitas."
    },
    {
      "id": "it-331e66c8f9738196a323f435fd7859d1",
      "nome": "Gaita de Fole",
      "tipo": "Insturmento Musical",
      "alcance": "",
      "empunhadura": "duas mãos",
      "habilidade": "",
      "preco": "300 Asterics",
      "qtdPorEspaco": 1,
      "tempoUso": "",
      "descricao": "Músicas tocadas com uma gaita de fole resistem na primeira vez que seriam interrompidas."
    },
    {
      "id": "it-331e66c8f97381efb14eee73c18a9ee7",
      "nome": "Gladius",
      "tipo": "Arma",
      "alcance": "Corpo a Corpo",
      "empunhadura": "uma mão",
      "habilidade": "Causa 1d6 + 1 de dano cortante.",
      "preco": "150-180 Asterics",
      "qtdPorEspaco": 1,
      "tempoUso": "Ação",
      "descricao": "Uma espada curta, resistente, ótima para cortar e aparar golpes."
    },
    {
      "id": "it-331e66c8f973810fae81e45b442c4116",
      "nome": "Harpa",
      "tipo": "Insturmento Musical",
      "alcance": "",
      "empunhadura": "duas mãos",
      "habilidade": "",
      "preco": "220 Asterics",
      "qtdPorEspaco": 1,
      "tempoUso": "",
      "descricao": "Músicas tocadas com a harpa aplicam modificador de Habilidade aos seus efeitos."
    },
    {
      "id": "it-331e66c8f9738134a1dfd757140ee381",
      "nome": "Harpa Grande",
      "tipo": "Imóvel Insturmento Musical",
      "alcance": "",
      "empunhadura": "duas mãos",
      "habilidade": "",
      "preco": "5000 Asterics",
      "qtdPorEspaco": 1,
      "tempoUso": "Ação",
      "descricao": "Músicas tocadas com a harpa aplicam o dobro modificador de Habilidade aos seus efeitos."
    },
    {
      "id": "it-331e66c8f97381ca9a3bc3c13804216d",
      "nome": "Kit de Forja (1 Carga)",
      "tipo": "Recarregar Kit",
      "alcance": "",
      "empunhadura": "",
      "habilidade": "",
      "preco": "40-50 Asterics",
      "qtdPorEspaco": 1,
      "tempoUso": "",
      "descricao": "Kit com diversas ferramentas e materiais, usado por forjadores"
    },
    {
      "id": "it-331e66c8f9738121b48bfebbb1aa83e2",
      "nome": "Kit médico (1 Carga)",
      "tipo": "Recarregar Kit",
      "alcance": "",
      "empunhadura": "",
      "habilidade": "",
      "preco": "30-40 Asterics",
      "qtdPorEspaco": 1,
      "tempoUso": "",
      "descricao": "Kit com diversos componentes medicinais, usado por um médico."
    },
    {
      "id": "it-331e66c8f9738146a9a3dec05d6ba92a",
      "nome": "Lança",
      "tipo": "Arma Arma de Caça",
      "alcance": "Longo Médio",
      "empunhadura": "duas mãos",
      "habilidade": "Causa 1d6 + 1 de dano perfurante.",
      "preco": "130-180 Asterics",
      "qtdPorEspaco": 1,
      "tempoUso": "Ação",
      "descricao": "Arremesso: Ataca de Longo alcance mas é desequipada. Descrição: Uma grande vara com uma ponta afiada, usada para espetar os inimigos e lutar com uma boa distância."
    },
    {
      "id": "it-331e66c8f97381028be0f709e3e75926",
      "nome": "Machado de Batalha",
      "tipo": "Arma",
      "alcance": "Corpo a Corpo",
      "empunhadura": "mão e meia",
      "habilidade": "Causa 1d6 + 3 Cortante",
      "preco": "190-220 Asterics",
      "qtdPorEspaco": 1,
      "tempoUso": "Ação",
      "descricao": "Um machado de cabo longo e lâmina curta, causa um impacto forte ao alvo."
    },
    {
      "id": "it-331e66c8f97381f988d7e6727df11aa4",
      "nome": "Manoplas de Combate",
      "tipo": "Arma",
      "alcance": "Corpo a Corpo",
      "empunhadura": "duas mãos",
      "habilidade": "Causa 1d6 de dano de impacto ao golpear com os punhos.",
      "preco": "230-270 Asterics",
      "qtdPorEspaco": 1,
      "tempoUso": "Ação",
      "descricao": "Luvas pesadas feitas de metal, potencializam o pode de golpes com os punhos. Seus ataques contam como ataques desarmados."
    },
    {
      "id": "it-342e66c8f9738094a305e2f62abf76e2",
      "nome": "Mapa da Área",
      "tipo": "Artefato",
      "alcance": "",
      "empunhadura": "",
      "habilidade": "Em posse do mapa, é impossível se perder na área mapeada.",
      "preco": "???",
      "qtdPorEspaco": 1,
      "tempoUso": "",
      "descricao": ""
    },
    {
      "id": "it-331e66c8f9738195be2cdf810044a2ed",
      "nome": "Maça",
      "tipo": "Arma",
      "alcance": "Corpo a Corpo",
      "empunhadura": "mão e meia",
      "habilidade": "Causa 1d6 Contundente + 2 Perfurante",
      "preco": "170-220 Asterics",
      "qtdPorEspaco": 1,
      "tempoUso": "Ação",
      "descricao": "Uma bola com espinhos ligada a um cabo grande ou corrente, usada para golpear os inimigos causando dano perfurante e contundente."
    },
    {
      "id": "it-331e66c8f97381508a2eda4350bf2cf1",
      "nome": "Munição Explosiva",
      "tipo": "Consumível",
      "alcance": "",
      "empunhadura": "",
      "habilidade": "Disparos causam +1d6 de dano mas perdem 1 nível de alcance.",
      "preco": "90-100 Asterics",
      "qtdPorEspaco": 3,
      "tempoUso": "",
      "descricao": "Disparos causam +1d6 de dano de queimadura mas perdem 1 nível de alcance"
    },
    {
      "id": "it-331e66c8f973810394e8eb394a2ae87d",
      "nome": "Munição Incandescente",
      "tipo": "Consumível",
      "alcance": "",
      "empunhadura": "",
      "habilidade": "Disparos causam +2 dano de fogo.",
      "preco": "70-80 Asterics",
      "qtdPorEspaco": 3,
      "tempoUso": "",
      "descricao": "Disparos causam +2 dano de fogo"
    },
    {
      "id": "it-331e66c8f97381ccbc98c08b5b7e8270",
      "nome": "Munição para Arma de fogo",
      "tipo": "Componente",
      "alcance": "",
      "empunhadura": "",
      "habilidade": "Recarrega 1 munição de uma arma de fogo.",
      "preco": "5-10",
      "qtdPorEspaco": 10,
      "tempoUso": "",
      "descricao": "Um conjunto de balas que pode ser usado para carregar uma arma de fogo."
    },
    {
      "id": "it-331e66c8f97381daa853f78ccac6c17b",
      "nome": "Ovos",
      "tipo": "Componente",
      "alcance": "",
      "empunhadura": "",
      "habilidade": "",
      "preco": "1-5 astrics",
      "qtdPorEspaco": 6,
      "tempoUso": "",
      "descricao": "Uma dúzia de ovos de um animal a sua escolha."
    },
    {
      "id": "it-331e66c8f9738157bd32e80333858e01",
      "nome": "Peças de metal",
      "tipo": "Componente",
      "alcance": "",
      "empunhadura": "",
      "habilidade": "",
      "preco": "15-25",
      "qtdPorEspaco": 5,
      "tempoUso": "",
      "descricao": "Pequenos pedaços de um metal comun."
    },
    {
      "id": "it-331e66c8f97381aebbbfd557aa4594fe",
      "nome": "Piano",
      "tipo": "Imóvel Insturmento Musical",
      "alcance": "",
      "empunhadura": "duas mãos",
      "habilidade": "Músicas Tocadas no Piano Aplicam o dobro do efeito.",
      "preco": "10000 Asterics",
      "qtdPorEspaco": 1,
      "tempoUso": "Ação",
      "descricao": "Manter uma música no piano consome uma ação, mas músicas tocadas no piano aplicam o dobro do efeito."
    },
    {
      "id": "it-331e66c8f973810fa5d3d0a41de9c1d5",
      "nome": "Poção Cerimônial",
      "tipo": "Componente Consumível",
      "alcance": "",
      "empunhadura": "",
      "habilidade": "Concede tontura por 6 hrs",
      "preco": "100-130 Asterics",
      "qtdPorEspaco": 1,
      "tempoUso": "Reação",
      "descricao": "Uma poção mágica feita com álcool e componentes alucinógenos, causa alucinações intensas em quem a consumir, sem um objetivo essa poção não serve de muita coisa."
    },
    {
      "id": "it-331e66c8f97381c39012ea682d2642e3",
      "nome": "Poção de Cura",
      "tipo": "Consumível",
      "alcance": "Corpo a Corpo",
      "empunhadura": "",
      "habilidade": "Cura 1d6 de vida.",
      "preco": "25-50",
      "qtdPorEspaco": 2,
      "tempoUso": "Reação",
      "descricao": "Uma bebida curativa, feita com ingredientes simples mas bem utilizados."
    },
    {
      "id": "it-331e66c8f97381f49ca6c90eab7e6f21",
      "nome": "Poção de Mana",
      "tipo": "Consumível",
      "alcance": "Corpo a Corpo",
      "empunhadura": "",
      "habilidade": "Recupera 1d6 de energia",
      "preco": "50-75",
      "qtdPorEspaco": 2,
      "tempoUso": "Reação",
      "descricao": "Uma bebida energética que ajuda a recuperar a energia de quem beber."
    },
    {
      "id": "it-331e66c8f9738197849be24c75bd239c",
      "nome": "Punhado de açúcar",
      "tipo": "Componente Consumível",
      "alcance": "",
      "empunhadura": "",
      "habilidade": "",
      "preco": "2-5 Asterics",
      "qtdPorEspaco": 5,
      "tempoUso": "",
      "descricao": "Pra adoçar a vida"
    },
    {
      "id": "it-331e66c8f9738190a951ca3df57af189",
      "nome": "Pólvora",
      "tipo": "Componente",
      "alcance": "",
      "empunhadura": "",
      "habilidade": "",
      "preco": "20-40",
      "qtdPorEspaco": 5,
      "tempoUso": "",
      "descricao": "Um punhado de pólvora,"
    },
    {
      "id": "it-331e66c8f973817fba5fceaed1cf9398",
      "nome": "Rede Enroscante",
      "tipo": "Ferramenta",
      "alcance": "Corpo a Corpo",
      "empunhadura": "uma mão",
      "habilidade": "",
      "preco": "100-120 Asterics",
      "qtdPorEspaco": 1,
      "tempoUso": "Ação",
      "descricao": "Uma rede feita de malha, projetada para enroscar alvos em meio a batalha. Imobiliza o alvo, ele pode fazer um teste de corpo ou técnica para se soltar."
    },
    {
      "id": "it-331e66c8f97381b89c4bed7b8ac498fb",
      "nome": "Relíquia Antiga",
      "tipo": "Artefato",
      "alcance": "",
      "empunhadura": "",
      "habilidade": "",
      "preco": "???",
      "qtdPorEspaco": 1,
      "tempoUso": "",
      "descricao": "Uma relíquia antiga que conta a história de onde foi encontrada, algumas relíquias podem ser extremamente valiosas dependendo de seu estado e raridade."
    },
    {
      "id": "it-331e66c8f97381f9b14cc1ecae5d657a",
      "nome": "Rifle",
      "tipo": "Arma Arma de Caça",
      "alcance": "Longo",
      "empunhadura": "duas mãos",
      "habilidade": "Causa 2d6 de dano perfurante.",
      "preco": "350-500",
      "qtdPorEspaco": 1,
      "tempoUso": "Ação",
      "descricao": "Uma arma de fogo que dispara a longas distancias, ela é recarregada a cada disparo. Consumindo 1 munição por disparo."
    },
    {
      "id": "it-331e66c8f9738116b2aac2745c4e7cd4",
      "nome": "Sangue de Soldado",
      "tipo": "Consumível",
      "alcance": "",
      "empunhadura": "",
      "habilidade": "Berserker: Aumente 2 de fúria.(Se sua fúria for 0 ela passa para 2) Não Berserker: Faça um teste de corpo, em uma falha você vomita perdendo 1 de corpo até o fim da cena, em um sucesso a bebida te motiva aumentando seu atributo Corpo em +1 até o fim da cena e te curando em 1d6.",
      "preco": "20-40",
      "qtdPorEspaco": 1,
      "tempoUso": "Ação",
      "descricao": "Essa Bebida avermelhada, picante e alcoólica, causa um arrepio no corpo todo e te deixa pronto para o combate."
    },
    {
      "id": "it-331e66c8f97381019a3fd3d9a3492f3c",
      "nome": "Semente Mágica",
      "tipo": "Componente Consumível",
      "alcance": "",
      "empunhadura": "",
      "habilidade": "",
      "preco": "1000-1500 Asterics",
      "qtdPorEspaco": 5,
      "tempoUso": "",
      "descricao": "Uma semente encantada, faz crescer plantas mágicas e podem ser usadas como componente de diversos rituais."
    },
    {
      "id": "it-331e66c8f9738174b6b3dd3d2778f3b5",
      "nome": "Sica curva",
      "tipo": "Arma",
      "alcance": "Corpo a Corpo",
      "empunhadura": "uma mão",
      "habilidade": "Causa 1d6 + 1 de dano cortante.",
      "preco": "200-230 Asterics",
      "qtdPorEspaco": 1,
      "tempoUso": "Ação",
      "descricao": "Uma espada torta, feita para atacar de ângulos diversos. Ignora metade do bloqueio do alvo."
    },
    {
      "id": "it-331e66c8f973813cba10f127faf14415",
      "nome": "Talismã",
      "tipo": "Artefato",
      "alcance": "",
      "empunhadura": "",
      "habilidade": "Alma +1 para o dono",
      "preco": "0",
      "qtdPorEspaco": 1,
      "tempoUso": "",
      "descricao": "Talismã básico criado pela receita “Talismã”. Ao seguir essa receita normalmente os xamãs encantam artefatos como colares, máscaras, totens, entre outros."
    },
    {
      "id": "it-331e66c8f973815aa297f3194be05297",
      "nome": "Tambor",
      "tipo": "Insturmento Musical",
      "alcance": "",
      "empunhadura": "duas mãos",
      "habilidade": "",
      "preco": "80-100 Asterics",
      "qtdPorEspaco": 1,
      "tempoUso": "",
      "descricao": "Músicas tocadas com o tambor aplicam modificador de Corpo nos seus efeitos."
    },
    {
      "id": "it-331e66c8f9738116b5eed37b2b6c4fb5",
      "nome": "Tridente",
      "tipo": "Arma",
      "alcance": "Médio",
      "empunhadura": "mão e meia",
      "habilidade": "Causa 1d6 + 3 de dano de perfuração.",
      "preco": "200-250 Asterics",
      "qtdPorEspaco": 1,
      "tempoUso": "Ação",
      "descricao": "Uma lança de 3 pontas menos aerodinâmica que uma lança normal mas causa um estrago maior."
    },
    {
      "id": "it-331e66c8f973811789e4f30603046909",
      "nome": "Troféu de caça",
      "tipo": "Componente",
      "alcance": "",
      "empunhadura": "",
      "habilidade": "",
      "preco": "???",
      "qtdPorEspaco": 1,
      "tempoUso": "",
      "descricao": "Uma parte de um alvo abatido durante uma caça, pode ser a presa de uma fera, as penas de um pássaro ou até partes de criaturas mágicas."
    },
    {
      "id": "it-331e66c8f97381d6a348fca605d49c84",
      "nome": "Vegetais",
      "tipo": "Componente",
      "alcance": "",
      "empunhadura": "",
      "habilidade": "",
      "preco": "5-25 asterics",
      "qtdPorEspaco": 5,
      "tempoUso": "",
      "descricao": "Vegetais a sua escolha, colhidos recentemente, são ótimos para preparar receitas."
    },
    {
      "id": "it-331e66c8f9738137b8bef5ebee0327b3",
      "nome": "Zarabatana",
      "tipo": "Arma Arma de Caça",
      "alcance": "Longo",
      "empunhadura": "uma mão",
      "habilidade": "Atira dardos no alvo",
      "preco": "80-100",
      "qtdPorEspaco": 1,
      "tempoUso": "Ação",
      "descricao": ""
    }
  ]
};
